import Head from "next/head";
import Image from "next/image";
import Quiz from "../components/Quiz";
import { QuizProvider } from "../context/quiz";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-black min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuizProvider>
        <Quiz />
      </QuizProvider>
    </div>
  );
}
